### ISSUE TITLE
Is 40-psm.rules needed?

### ISSUE THREAD

**Issue by bsmith94** [01org/opa-psm2#26]
opa-psm2 installs /lib/udev/rules.d/40-psm.rules, which sets the permissions of the hfi1 devices to 0666. As the hfi1 driver already sets the permission to 0666, is this rules definition still needed?

**Comment by rwmcguir** [comment]
So research on this indicates that while the latest upstream kernels (and latest distros) no longer need this rules file, the backwards compatible with older hfi1 drivers that do not set this, i.e. older RHEL 7 stuff. We are doing inquiries to see how far back we want to maintain compatibility.

**Comment by mwheinz** [comment]
There is no plan to remove 40-psm.rules at this time.
