### ISSUE TITLE
autotools

### ISSUE THREAD

**Issue by jeffhammond** [01org/opa-psm2#3]
In order to build PSM2 from source using an installation of libuuid that is not in `/usr`, one has to hack `buildflags.mak` by hand.  It would be nice if PSM2 had an autotools-based build system that was flexible w.r.t. the paths of its dependencies.  Another benefit is the potential to support out-of-place builds.

If you are amenable to autotools but do not have the resources to implement it, I will try to work on it.  (I am employed by Intel, in case it matters.)

**Comment by pjreger** [comment]
Hi,

Just to let anyone know who is subscribed to this list, I am working directly, offline with Jeff on this topic.  If anyone is interested in this topic, please let me know and I will copy you or the list – depending on the interest level.

Thanks,

Paul Reger
503 613 4617
paul.j.reger@intel.commailto:paul.j.reger@intel.com
