### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by QwertyJack** [01org/opa-psm2#38]
Is there any instruction on Ubuntu? Either xenial or bionic is well.

**Comment by bmyates** [comment]
Sorry, Ubuntu is not currently one of our supported distros

**Comment by QwertyJack** [comment]
Why not ?

**Comment by bsmith94** [comment]
@QwertyJack Have you tried this? https://launchpad.net/ubuntu/+source/libpsm2

**Comment by QwertyJack** [comment]
@bsmith94 It works like a charm. Thank you very much !

**Comment by QwertyJack** [comment]
The psm2 package is released in libfabric which is now only available in cosmic(18.10) and above ([see here](https://launchpad.net/ubuntu/+source/libfabric/+changelog#libfabric_1.6.1-1)).
The above link is quite fine tested under bionic.
