### ISSUE TITLE
PSM2 with GPU

### ISSUE THREAD

**Issue by shruticd** [01org/opa-psm2#70]
Hi, 
I tried to execute Mvapich-3.0 with OFI, psm2 as the provider. The installation runs well within node but gives out a segmentation fault across nodes. Why does this happen?

**Comment by ddalessa** [comment]
Which GPU are you attempting to run with?

Why are you trying to run with psm2 as the provider? That is not the recommended way. You should be using OPX as the provider. This GitHub project is for psm2. Problems with OFI should probably start with libfabric GitHub project. Has this been reported there and is there any other information that points to the psm2 library as being the issue?

Keep in mind the psm2 provider in OFI is not a native provider. It is a set of wrappers around the libpsm2 library (this project).

**Comment by shruticd** [comment]
Actually the issue was with the benchmarks, I was testing the configuration on. It is working well with Intel MPI GPU Benchmarks.
