### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by danghvu** [01org/opa-psm2#9]
Where can I find some examples for working with PSM2 ?

Something like a pingpong latency test would be helpful.

Thank you

**Comment by ravindra-ganapathi** [comment]
Section 5 of the PSM2 programmer's guide

www.intel.com/content/dam/support/us/en/documents/network-and-i-o/fabric-products/Intel_PSM2_PG_H76473_v5_0.pdf

Thanks,
Ravi

**Comment by matcabral** [comment]
Hi @danghvu,  
If you want to see an example of an MPI implementation of PSM2 support, you may find Open MPI here:
https://github.com/open-mpi/ompi/tree/master/ompi/mca/mtl/psm2

Libfabric psm2 provider:
https://github.com/ofiwg/libfabric/tree/master/prov/psm2/src

**Comment by danghvu** [comment]
Thank you!

These should be sufficient resources for my purposes.
But I think It would be helpful to others if there is an "example" directory in the library source. 
If you are open for PR I could make that happens during my free time.

**Comment by matcabral** [comment]
We are open for PRs! Please share examples if you find value in them. 
thanks,
